# Pipeline for continuous integration and deployment
name : CI pipeline

on:
#  initiates the pipeline whenever user pushes on the main branch
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Test is running on ubuntu machine

    # setting up the environment variables for the application
    env:
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

    steps:
      - name: Clone and checkout to the repository
        uses: actions/checkout@v4 # Clones the repository in the working directory of the runner

      - name: Setting up Python
        uses: actions/setup-python@v5 # setting up the python environment to version 3.9
        with:
          python-version: "3.9"

      - name: Installing dependencies # installing the required dependencies for the application
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Run tests
        run:
           python app/tests/__init__.py # running the __init__.py under app/tests
